export default {
  actions_a: {
    category: 'Actions (set A)',
    route: '/category/actions_a',
    words: [
      {
        word: 'Cry',
        translation: 'Плакать',
        image: '../../../assets/images/actions_a/cry.jpg',
        audioSrc: '../../../assets/sounds/actions_a/cry.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Dance',
        translation: 'Танцевать',
        image: '../../../assets/images/actions_a/dance.jpg',
        audioSrc: '../../../assets/sounds/actions_a/dance.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Dive',
        translation: 'Нырять',
        image: '../../../assets/images/actions_a/dive.jpg',
        audioSrc: '../../../assets/sounds/actions_a/dive.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Draw',
        translation: 'Рисовать',
        image: '../../../assets/images/actions_a/draw.jpg',
        audioSrc: '../../../assets/sounds/actions_a/draw.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Fly',
        translation: 'Летать',
        image: '../../../assets/images/actions_a/fly.jpg',
        audioSrc: '../../../assets/sounds/actions_a/fly.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Open',
        translation: 'Открывать',
        image: '../../../assets/images/actions_a/open.jpg',
        audioSrc: '../../../assets/sounds/actions_a/open.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Play',
        translation: 'Играть',
        image: '../../../assets/images/actions_a/play.jpg',
        audioSrc: '../../../assets/sounds/actions_a/play.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Ride',
        translation: 'Ездить',
        image: '../../../assets/images/actions_a/ride.jpg',
        audioSrc: '../../../assets/sounds/actions_a/ride.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  actions_b: {
    category: 'Actions (set B)',
    route: '/category/actions_b',
    words: [
      {
        word: 'Hug',
        translation: 'Обнимать',
        image: '../../../assets/images/actions_b/hug.jpg',
        audioSrc: '../../../assets/sounds/actions_b/hug.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Jump',
        translation: 'Прыгать',
        image: '../../../assets/images/actions_b/jump.jpg',
        audioSrc: '../../../assets/sounds/actions_b/jump.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Meet',
        translation: 'Знакомиться',
        image: '../../../assets/images/actions_b/meet.jpg',
        audioSrc: '../../../assets/sounds/actions_b/meet.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Point',
        translation: 'Указывать',
        image: '../../../assets/images/actions_b/point.jpg',
        audioSrc: '../../../assets/sounds/actions_b/point.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Run',
        translation: 'Бегать',
        image: '../../../assets/images/actions_b/run.jpg',
        audioSrc: '../../../assets/sounds/actions_b/run.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Sing',
        translation: 'Петь',
        image: '../../../assets/images/actions_b/sing.jpg',
        audioSrc: '../../../assets/sounds/actions_b/sing.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Skip',
        translation: 'Пропускать, прыгать',
        image: '../../../assets/images/actions_b/skip.jpg',
        audioSrc: '../../../assets/sounds/actions_b/skip.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Swim',
        translation: 'Плавать',
        image: '../../../assets/images/actions_b/swim.jpg',
        audioSrc: '../../../assets/sounds/actions_b/swim.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  animals_a: {
    category: 'Animals (set A)',
    route: '/category/animals_a',
    words: [
      {
        word: 'Bird',
        translation: 'Птица',
        image: '../../../assets/images/animals_a/bird.jpg',
        audioSrc: '../../../assets/sounds/animals_a/bird.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Cat',
        translation: 'Кот',
        image: '../../../assets/images/animals_a/cat.jpg',
        audioSrc: '../../../assets/sounds/animals_a/cat.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Chicken',
        translation: 'Курица',
        image: '../../../assets/images/animals_a/chicken.jpg',
        audioSrc: '../../../assets/sounds/animals_a/chicken.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Dog',
        translation: 'Собака',
        image: '../../../assets/images/animals_a/dog.jpg',
        audioSrc: '../../../assets/sounds/animals_a/dog.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Dolphin',
        translation: 'Дельфин',
        image: '../../../assets/images/animals_a/dolphin.jpg',
        audioSrc: '../../../assets/sounds/animals_a/dolphin.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Fish',
        translation: 'Рыба',
        image: '../../../assets/images/animals_a/fish.jpg',
        audioSrc: '../../../assets/sounds/animals_a/fish.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Frog',
        translation: 'Жаба',
        image: '../../../assets/images/animals_a/frog.jpg',
        audioSrc: '../../../assets/sounds/animals_a/frog.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Giraffe',
        translation: 'Жираф',
        image: '../../../assets/images/animals_a/giraffe.jpg',
        audioSrc: '../../../assets/sounds/animals_a/giraffe.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  animals_b: {
    category: 'Animals (set B)',
    route: '/category/animals_b',
    words: [
      {
        word: 'Chick',
        translation: 'Цыплёнок',
        image: '../../../assets/images/animals_b/chick.jpg',
        audioSrc: '../../../assets/sounds/animals_b/chick.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Horse',
        translation: 'Лошадь',
        image: '../../../assets/images/animals_b/horse.jpg',
        audioSrc: '../../../assets/sounds/animals_b/horse.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Lion',
        translation: 'Лев',
        image: '../../../assets/images/animals_b/lion.jpg',
        audioSrc: '../../../assets/sounds/animals_b/lion.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Mouse',
        translation: 'Мышь',
        image: '../../../assets/images/animals_b/mouse.jpg',
        audioSrc: '../../../assets/sounds/animals_b/mouse.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Pig',
        translation: 'Свинья',
        image: '../../../assets/images/animals_b/pig.jpg',
        audioSrc: '../../../assets/sounds/animals_b/pig.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Rabbit',
        translation: 'Кролик',
        image: '../../../assets/images/animals_b/rabbit.jpg',
        audioSrc: '../../../assets/sounds/animals_b/rabbit.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Sheep',
        translation: 'Овца',
        image: '../../../assets/images/animals_b/sheep.jpg',
        audioSrc: '../../../assets/sounds/animals_b/sheep.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Turtle',
        translation: 'Черепаха',
        image: '../../../assets/images/animals_b/turtle.jpg',
        audioSrc: '../../../assets/sounds/animals_b/turtle.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  clothes: {
    category: 'Clothes',
    route: '/category/clothes',
    words: [
      {
        word: 'Blouse',
        translation: 'Блузка',
        image: '../../../assets/images/clothes/blouse.jpg',
        audioSrc: '../../../assets/sounds/clothes/blouse.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Boot',
        translation: 'Ботинок',
        image: '../../../assets/images/clothes/boot.jpg',
        audioSrc: '../../../assets/sounds/clothes/boot.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Coat',
        translation: 'Пальто',
        image: '../../../assets/images/clothes/coat.jpg',
        audioSrc: '../../../assets/sounds/clothes/coat.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Dress',
        translation: 'Платье',
        image: '../../../assets/images/clothes/dress.jpg',
        audioSrc: '../../../assets/sounds/clothes/dress.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Pants',
        translation: 'Брюки',
        image: '../../../assets/images/clothes/pants.jpg',
        audioSrc: '../../../assets/sounds/clothes/pants.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Shirt',
        translation: 'Рубашка',
        image: '../../../assets/images/clothes/shirt.jpg',
        audioSrc: '../../../assets/sounds/clothes/shirt.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Shoe',
        translation: 'Туфли',
        image: '../../../assets/images/clothes/shoe.jpg',
        audioSrc: '../../../assets/sounds/clothes/shoe.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Skirt',
        translation: 'Юбка',
        image: '../../../assets/images/clothes/skirt.jpg',
        audioSrc: '../../../assets/sounds/clothes/skirt.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  emotions: {
    category: 'Emotions',
    route: '/category/emotions',
    words: [
      {
        word: 'Angry',
        translation: 'Сердитый',
        image: '../../../assets/images/emotions/angry.jpg',
        audioSrc: '../../../assets/sounds/emotions/angry.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Happy',
        translation: 'Счастливый',
        image: '../../../assets/images/emotions/happy.jpg',
        audioSrc: '../../../assets/sounds/emotions/happy.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Laugh',
        translation: 'Смех',
        image: '../../../assets/images/emotions/laugh.jpg',
        audioSrc: '../../../assets/sounds/emotions/laugh.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Sad',
        translation: 'Грустный',
        image: '../../../assets/images/emotions/sad.jpg',
        audioSrc: '../../../assets/sounds/emotions/sad.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Scared',
        translation: 'Испуганный',
        image: '../../../assets/images/emotions/scared.jpg',
        audioSrc: '../../../assets/sounds/emotions/scared.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Smile',
        translation: 'Улыбка',
        image: '../../../assets/images/emotions/smile.jpg',
        audioSrc: '../../../assets/sounds/emotions/smile.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Surprised',
        translation: 'Удивлённый',
        image: '../../../assets/images/emotions/surprised.jpg',
        audioSrc: '../../../assets/sounds/emotions/surprised.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Tired',
        translation: 'Уставший',
        image: '../../../assets/images/emotions/tired.jpg',
        audioSrc: '../../../assets/sounds/emotions/tired.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  fruits: {
    category: 'Fruits',
    route: '/category/fruits',
    words: [
      {
        word: 'Apple',
        translation: 'Яблоко',
        image: '../../../assets/images/fruits/apple.jpg',
        audioSrc: '../../../assets/sounds/fruits/apple.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Apricot',
        translation: 'Абрикос',
        image: '../../../assets/images/fruits/apricot.jpg',
        audioSrc: '../../../assets/sounds/fruits/apricot.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Banana',
        translation: 'Банан',
        image: '../../../assets/images/fruits/banana.jpg',
        audioSrc: '../../../assets/sounds/fruits/banana.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Grape',
        translation: 'Виноград',
        image: '../../../assets/images/fruits/grape.jpg',
        audioSrc: '../../../assets/sounds/fruits/grape.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Orange',
        translation: 'Апельсин',
        image: '../../../assets/images/fruits/orange.jpg',
        audioSrc: '../../../assets/sounds/fruits/orange.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Peach',
        translation: 'Персик',
        image: '../../../assets/images/fruits/peach.jpg',
        audioSrc: '../../../assets/sounds/fruits/peach.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Pear',
        translation: 'Груша',
        image: '../../../assets/images/fruits/pear.jpg',
        audioSrc: '../../../assets/sounds/fruits/pear.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Pineapple',
        translation: 'Ананас',
        image: '../../../assets/images/fruits/pineapple.jpg',
        audioSrc: '../../../assets/sounds/fruits/pineapple.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
  transport: {
    category: 'Transport',
    route: '/category/transport',
    words: [
      {
        word: 'Bicycle',
        translation: 'Велосипед',
        image: '../../../assets/images/transport/bicycle.jpg',
        audioSrc: '../../../assets/sounds/transport/bicycle.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Bus',
        translation: 'Автобус',
        image: '../../../assets/images/transport/bus.jpg',
        audioSrc: '../../../assets/sounds/transport/bus.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Car',
        translation: 'Автомобиль',
        image: '../../../assets/images/transport/car.jpg',
        audioSrc: '../../../assets/sounds/transport/car.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Motorcycle',
        translation: 'Мотоцикл',
        image: '../../../assets/images/transport/motorcycle.jpg',
        audioSrc: '../../../assets/sounds/transport/motorcycle.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Ship',
        translation: 'Корабль',
        image: '../../../assets/images/transport/ship.jpg',
        audioSrc: '../../../assets/sounds/transport/ship.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Subway',
        translation: 'Метро',
        image: '../../../assets/images/transport/subway.jpg',
        audioSrc: '../../../assets/sounds/transport/subway.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Train',
        translation: 'Поезд',
        image: '../../../assets/images/transport/train.jpg',
        audioSrc: '../../../assets/sounds/transport/train.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
      {
        word: 'Truck',
        translation: 'Грузовик',
        image: '../../../assets/images/transport/truck.jpg',
        audioSrc: '../../../assets/sounds/transport/truck.mp3',
        clicks: 0,
        correct: 0,
        wrong: 0,
        winPercent: 0,
      },
    ],
  },
};
